"""
Source code to LaTeX converter.
"""


from pygments import highlight
from pygments.lexers import guess_lexer, guess_lexer_for_filename
from pygments.formatters import LatexFormatter
from pygments.styles import get_style_by_name


LATEX_PREAMBLE = """
\\usepackage[top=0.3in, bottom=0.3in, right=0.5in, left=0.5in]{{geometry}}

\\usepackage[dvipsnames]{{xcolor}}
\\definecolor{{background}}{{HTML}}{{{bgcolor}}}
\\pagecolor{{background}}

\\pagenumbering{{gobble}}
"""


def source_to_latex(
    source_code: str, filename: str | None = None, style: str = 'default'
) -> str:
    """
    Returns LaTeX code generated by pygments from `source_code`.
    """

    if filename is None:
        lexer = guess_lexer(source_code)
    else:
        lexer = guess_lexer_for_filename(filename, source_code)

    bgcolor = get_style_by_name(style).background_color
    preamble = LATEX_PREAMBLE.format(bgcolor=bgcolor[1:])

    formatter = LatexFormatter(full=True,style=style,preamble=preamble)
    latex_code = highlight(source_code, lexer, formatter)

    return latex_code
