[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "code_to_pdf"
version = "1.0.0"
dependencies = [
    "pygments",
]

[project.scripts]
code-to-pdf = "code_to_pdf.cli:main"
